Repository go-vela/mock, pull requests merged in 2019-12, with the labels that each got.

#15 Release v0.2.0-rc2
  go.mod
  go.sum
Labels: enhancement

#16 Update gin gonic to latest release
  go.mod
  go.sum
Labels: enhancement

#17 Add Actions pipeline for changelog
  .chglog/CHANGELOG.tpl.md
  .chglog/config.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/validate.yml
Labels: feature

#18 ci: ignore release candidate for changelog
  .github/workflows/release.yml
Labels: enhancement

#19 feat(build): add email and link fields
  go.mod
  go.sum
  server/build.go
Labels: feature

#20 chore: update go-vela/types dependency
  go.mod
  go.sum
Labels: enhancement

#21 ci: switch from coveralls to codecov
  .github/README.md
  .github/workflows/test.yml
Labels: enhancement

#22 ci: add explicit configuration for automation
  .golangci.yml
  codecov.yml
Labels: enhancement

#23 refactor: fix linter errors
  server/build.go
  server/log.go
  server/repo.go
  server/secret.go
  server/service.go
  server/step.go
Labels: enhancement

#24 chore: update for v0.2.0
  go.mod
  go.sum
Labels: dependencies

#25 ci(linters): update funlen linter settings
  .golangci.yml
Labels: enhancement
