Repository go-vela/mock, pull requests merged in 2020-04, with the labels that each got.

#43 chore: update for v0.4.0-rc1
  go.mod
  go.sum
Labels: dependencies

#45 feat(docker): add volume not found checks
  docker/volume.go
Labels: feature

#44 feat(docker): add network not found checks
  docker/network.go
Labels: feature

#46 feat(server): add deployment endpoints
  go.mod
  go.sum
  server/deployment.go
  server/server.go
Labels: feature

#48 feat(server): add hook endpoints
  server/hook.go
  server/server.go
Labels: feature

#49 chore: update version to v0.4.0-rc3
  go.mod
  go.sum
Labels: dependencies

#50 refactor(server): update deployment values
  server/deployment.go
Labels: enhancement
