Repository go-vela/mock, pull requests merged in 2020-07, with the labels that each got.

#59 ci: refactor Makefile. improve linter setup. upgrade deps.
  .github/workflows/release.yml
  .github/workflows/reviewdog.yml
  .github/workflows/test.yml
  .github/workflows/validate.yml
  .golangci.yml
  Makefile
  codecov.yml
  go.mod
  go.sum
Labels: dependencies, enhancement

#60 fix: update mock to return JSON results
  server/build.go
  server/hook.go
  server/log.go
  server/repo.go
  server/secret.go
  server/service.go
  server/step.go
Labels: bug

#61 chore: update go mod for v0.5.0-rc1
  go.mod
  go.sum
Labels: dependencies
